//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHostService")]
public interface IHostService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService/TransferGameBoard", ReplyAction="http://tempuri.org/IHostService/TransferGameBoardResponse")]
    void TransferGameBoard();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService/TransferGameBoard", ReplyAction="http://tempuri.org/IHostService/TransferGameBoardResponse")]
    System.Threading.Tasks.Task TransferGameBoardAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHostServiceChannel : IHostService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HostServiceClient : System.ServiceModel.ClientBase<IHostService>, IHostService
{
    
    public HostServiceClient()
    {
    }
    
    public HostServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HostServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void TransferGameBoard()
    {
        base.Channel.TransferGameBoard();
    }
    
    public System.Threading.Tasks.Task TransferGameBoardAsync()
    {
        return base.Channel.TransferGameBoardAsync();
    }
}
